// import head component
import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Christine Madec - Psychologue</title>
                <meta name="description" content="Generated by create next app"/>

            </Head>

            {/* rest code here */}
        </>
    );
}